// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_G0ZU4_3vldrYXYg2LjyyNy7M88YAEaw',
    appId: '1:1049704081022:web:0e734829e2d458c87a9a2f',
    messagingSenderId: '1049704081022',
    projectId: 'flutter-todo-e7e8a',
    authDomain: 'flutter-todo-e7e8a.firebaseapp.com',
    storageBucket: 'flutter-todo-e7e8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLmQFUI93uRXPx7_ipq50U3rE5UhO54F0',
    appId: '1:1049704081022:android:a8231b57baba01c17a9a2f',
    messagingSenderId: '1049704081022',
    projectId: 'flutter-todo-e7e8a',
    storageBucket: 'flutter-todo-e7e8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4ZifIc4byhs_CW2pXsLL_aJOdB2FTZg',
    appId: '1:1049704081022:ios:60e87c02b43087447a9a2f',
    messagingSenderId: '1049704081022',
    projectId: 'flutter-todo-e7e8a',
    storageBucket: 'flutter-todo-e7e8a.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4ZifIc4byhs_CW2pXsLL_aJOdB2FTZg',
    appId: '1:1049704081022:ios:f61d4c9f6fc958457a9a2f',
    messagingSenderId: '1049704081022',
    projectId: 'flutter-todo-e7e8a',
    storageBucket: 'flutter-todo-e7e8a.appspot.com',
    iosBundleId: 'com.example.todoApplication.RunnerTests',
  );
}
